# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.box = "centos/8"
  config.vm.define "gitlab"

  config.vm.network "private_network", ip: "172.16.0.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3096"
    vb.cpus = "2"
    vb.name = "gitlab"
    vb.default_nic_type = "virtio"
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      vb.customize ["modifyvm", :id, "--vram", "16"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--uart1", "off"]
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
      vb.customize ["modifyvm", :id, "--usbohci", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
      vb.customize ["modifyvm", :id, "--usbxhci", "off"]
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.hostname = "gitlab.dreamenv.com"
end